import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkGfm from "remark-gfm";
import remarkDirective from "remark-directive";
import type { Root } from "mdast";
import { annotateLessonRefs, type RefMark } from "@/lib/glossary/annotate";
import { buildRefRegistry, type RefModule } from "@/lib/refs/registry";

/**
 * The golden reference report: every lesson/module mention the annotator links, per locale, in
 * reading order — the sibling of the glossary's `glossary-links.<locale>.txt`, under the same
 * discipline. Reviewed once by eye, then frozen: a content edit that moves, adds or drops a
 * reference shows up as a diff in `content/lesson-refs.<locale>.txt` rather than silently in the
 * book.
 *
 * Both axes are permanent KEYS — the source lesson and the target — so a future display renumbering
 * only diffs the mention column, which is the prose itself and genuinely changed. Dangling mentions
 * are carried in the report's own type so the suite can assert there are none: that assertion is the
 * course's prose-integrity guard, not a rendering detail.
 */

const processor = unified().use(remarkParse).use(remarkGfm).use(remarkDirective);

export interface RefReportLesson {
  /** Display id — what mentions are written in, and what self-reference means. */
  id: string;
  /** Permanent key — the report's source axis. */
  key: string;
  markdown: string;
}

export interface RefReportRow {
  lessonKey: string;
  /** The mention as written in the prose. */
  mention: string;
  kind: "module" | "lesson";
  targetKey: string;
  context: string;
}

export interface RefReport {
  locale: string;
  /** Mentions that carry a link, in course reading order. */
  rows: RefReportRow[];
  /** Mentions of the page they sit on — deliberately unlinked, listed so the decision is visible. */
  self: RefReportRow[];
  /** Id-shaped tokens no entity answers to. The suite asserts this stays empty. */
  dangling: { lessonKey: string; mention: string; context: string }[];
}

function row(mark: RefMark, lessonKey: string): RefReportRow {
  return {
    lessonKey,
    mention: mark.mention,
    kind: mark.refKind as "module" | "lesson",
    targetKey: mark.refKey as string,
    context: mark.context,
  };
}

/** `lessons` must be in course reading order; `modules` is the manifest, keys included. */
export function buildRefReport(
  lessons: RefReportLesson[],
  modules: RefModule[],
  locale: string,
): RefReport {
  const registry = buildRefRegistry(modules);
  const report: RefReport = { locale, rows: [], self: [], dangling: [] };
  for (const lesson of lessons) {
    const tree: Root = processor.parse(lesson.markdown);
    const found = annotateLessonRefs(tree, { lessonId: lesson.id, registry });
    report.rows.push(...found.marks.map((mark) => row(mark, lesson.key)));
    report.self.push(...found.self.map((mark) => row(mark, lesson.key)));
    report.dangling.push(
      ...found.dangling.map((mark) => ({
        lessonKey: lesson.key,
        mention: mark.mention,
        context: mark.context,
      })),
    );
  }
  return report;
}

/** Fixed columns, one reference per line: a diff points at the lesson and the mention that moved. */
export function formatRefReport(report: RefReport): string {
  const lessons = new Set(report.rows.map((row) => row.lessonKey)).size;
  const lines = [
    `# lesson references — ${report.locale}`,
    "#",
    "# Generated by lib/refs/report.test.ts from content/. Reviewed by hand, then frozen: any content",
    "# change that moves, adds or drops a reference shows up here as a diff. Do not hand-edit — fix",
    "# the prose and regenerate.",
    "#",
    `# ${report.rows.length} references from ${lessons} lessons · ` +
      `${report.self.length} self-mentions deliberately unlinked · ${report.dangling.length} dangling`,
    "#",
    "# lesson   mention  target          context, with the mention in «»",
  ];
  for (const row of report.rows) {
    lines.push(
      [
        row.lessonKey.padEnd(8),
        row.mention.padEnd(8),
        `${row.kind} ${row.targetKey}`.padEnd(15),
        row.context,
      ].join(" "),
    );
  }
  lines.push(
    "#",
    "# Self-mentions: the mention names the page it sits on, so a link would go nowhere new.",
    ...report.self.map(
      (row) => `#   ${row.lessonKey.padEnd(8)} ${row.mention.padEnd(8)} ${row.context}`,
    ),
  );
  if (report.dangling.length > 0) {
    lines.push(
      "#",
      "# DANGLING — id-shaped mentions that resolve to nothing. The suite fails while this list exists:",
      ...report.dangling.map(
        (entry) => `#   ${entry.lessonKey.padEnd(8)} ${entry.mention.padEnd(8)} ${entry.context}`,
      ),
    );
  }
  return `${lines.join("\n")}\n`;
}
