# SPDX-License-Identifier: AGPL-3.0-only
"""Stage the Phase W1 libm-parity artifacts as a contract the Android port can consume.

Phase W2. The other two contract exporters COMPUTE what they write; this one does not. The parity
measurement is expensive (a ~2M-input sweep, a 124 MB uncommitted full stream) and its whole value is
that it was taken once, on a recorded machine, against a recorded glibc. Re-measuring during an
export would silently re-baseline the very thing being pinned. So the artifacts are produced by
`measure_libm_parity.py`, committed, and this script copies them across with a README that stands on
its own in the other repository.

What the Android side does with them. It evaluates `StrictMath.exp`/`StrictMath.log` over the
`input` column and compares against `numpy` — the values the goldens were actually captured from.
That comparison is INFORMATIONAL and must never fail a build: Phase W1 measured the disagreement at
1 ulp on 4.86% of `exp` inputs and 0.79% of `log` inputs, and measured that perturbing every result
by a full ulp moved zero of 845 document fingerprints. The binding contract is the rounded payload in
`generation-goldens/`. This directory exists so a port that IS failing can tell a libm difference
apart from a real bug, and so the count is watched rather than assumed.

Usage (from `backend/`):
    uv run python scripts/export_libm_parity.py
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

_BACKEND = Path(__file__).resolve().parent.parent
REPO = _BACKEND.parent
SCRIPTS = _BACKEND / "scripts"
ARTIFACT_DIR = SCRIPTS / "artifacts"
KOTLIN_SIDE_DIR = SCRIPTS / "kotlin_side"

DEFAULT_OUT = REPO / "dist" / "contracts" / "libm-parity"

#: How to rebuild the inputs this script only copies, quoted in every refusal so the fix is in hand.
REGENERATE = "uv run python scripts/measure_libm_parity.py"

#: Every file that crosses into the Android repository, and what it is for. Named as one list so a
#: missing artifact is a loud refusal rather than a short directory nobody counts.
DELIVERED: tuple[tuple[Path, str, str], ...] = (
    (
        ARTIFACT_DIR / "libm-parity-sample.tsv",
        "libm-parity-sample.tsv",
        "the measured rows: one input per line with NumPy's and glibc's answers, as bit patterns",
    ),
    (
        ARTIFACT_DIR / "libm-parity-domain.json",
        "libm-parity-domain.json",
        "the closed interval each function is called on anywhere in the generation path",
    ),
    (
        ARTIFACT_DIR / "libm-parity-summary.json",
        "libm-parity-summary.json",
        "counts, the recording environment, and SHA-256 digests over the COMPLETE streams",
    ),
    (
        KOTLIN_SIDE_DIR / "LibmParityCheck.java",
        "LibmParityCheck.java",
        "the runnable JVM reference: `java LibmParityCheck.java libm-parity-sample.tsv`",
    ),
)


class ParityExportError(RuntimeError):
    """An artifact this script only copies was missing, so there is nothing honest to write."""


def missing_sources() -> list[Path]:
    return [source for source, _name, _what in DELIVERED if not source.is_file()]


def readme_text(summary: dict, domain: dict) -> str:
    """The spec as the Android repository reads it — it has no access to this repo's scripts."""
    functions = summary["functions"]
    environment = summary["environment"]
    rows = "\n".join(
        f"| `{name}` | {what} |" for _source, name, what in DELIVERED
    )
    per_function = "\n".join(
        f"| `{fn}` | {functions[fn]['calls']:,} | {functions[fn]['distinct_inputs']:,} | "
        f"{domain['domains'][fn]['min']!r} | {domain['domains'][fn]['max']!r} |"
        for fn in sorted(functions)
    )
    digests = "\n".join(
        f"| `{fn}` | `{functions[fn]['digests']['inputs']}` | `{functions[fn]['digests']['numpy']}` |"
        for fn in sorted(functions)
    )
    sampled = summary["sample_rows"]
    total = summary["total_distinct_inputs"]
    return f"""<!-- SPDX-License-Identifier: AGPL-3.0-only -->
# libm parity

Generated by `backend/scripts/export_libm_parity.py` in the TradeSchool web repository, which copies
artifacts recorded once by `backend/scripts/measure_libm_parity.py`. Do not hand-edit: regenerate,
and read the diff.

Every close price in this course is `base * exp(shape + noise)`, and every log-scale reading goes
back through `log`. Neither function is required by IEEE-754 to be correctly rounded, so two correct
implementations may return doubles that differ in the last bit. The Python reference ran against
**{environment["libc"]}**; the Android port calls `StrictMath`, which is fdlibm — a different
algorithm, identical on every JVM and CPU. These files are the measured difference between them.

## The files

| file | what it is |
| --- | --- |
{rows}

## What a port asserts, and what it must not

Evaluate `StrictMath.exp` / `StrictMath.log` on the `input` column and compare with `numpy`.

**Report the mismatch count. Never fail on it.** Phase W1 measured the disagreement at 1 ulp on
4.86% of `exp` inputs and 0.79% of `log` inputs, then perturbed *every* `exp`/`log` result by a full
ulp and re-derived the goldens: **zero** of 845 document fingerprints moved. The rounding to 2 and 4
decimals that every payload passes through absorbs the last bit. So the binding cross-language
contract is `../generation-goldens/`, and a raw-double comparison here is a debugging instrument —
it tells a port whether a divergence is a libm difference this project has decided to tolerate or a
real bug in the port.

Use `StrictMath`, never `Math`. `Math.exp` is a platform intrinsic that may differ from
`StrictMath.exp` with no stated bound; `StrictMath` is specified to fdlibm's exact algorithm, which
is why the port can be reproducible at all.

`LibmParityCheck.java` answers Phase W1's narrower question — *are they bit-identical?* — and so
prints `PARITY BROKEN` and **exits 1** whenever any row differs. On this artifact it always will.
That is the expected result, not a regression: do not wire its exit code to a build. Read the
per-function mismatch counts it prints, and compare them to the table below.

## Format

`libm-parity-sample.tsv` is a TSV. Lines starting with `#` are a header; the first line that does not
is the column header; every line after it is a row.

| column | meaning |
| --- | --- |
| `fn` | `exp` or `log` |
| `input` | the argument, as an IEEE-754 bit pattern (`0x` + 16 hex digits, big-endian) |
| `numpy` | what NumPy returned — **the value the goldens were captured from** |
| `libm` | what C `math.exp`/`math.log` returned, so the artifact shows if NumPy's kernel IS the libm |

Nothing is rounded anywhere: a port comparing printed decimals is comparing roundings, and two libms
may agree on the double and disagree on its 17th digit.

## What was measured

| function | calls | distinct inputs | domain min | domain max |
| --- | --- | --- | --- | --- |
{per_function}

A from-scratch `exp`/`log` would only have to be right on those intervals — but right for every
double in them, not only the ones this sweep happened to hit.

The file carries **{sampled:,} of {total:,}** distinct inputs: an even stride over the sorted domain,
both endpoints, plus every row where NumPy and the platform libm disagreed. The complete stream is
not committed ({environment["platform"]} produced ~124 MB of it); regenerate it with
`{REGENERATE} --full` and verify it against these digests over the full streams:

| function | inputs | numpy outputs |
| --- | --- | --- |
{digests}

## Recording environment

| | |
| --- | --- |
| python | {environment["python"]} |
| numpy | {environment["numpy"]} |
| libc | {environment["libc"]} |
| platform | {environment["platform"]} |
| machine | {environment["machine"]} |

Documents swept: {summary["documents_generated"]:,} over {summary["probe_seeds"]} probe seeds,
{summary["documents_refused"]} refused.
"""


def deliver(out: Path) -> list[str]:
    """Copy every delivered artifact into `out` and write the README. Returns the names written."""
    absent = missing_sources()
    if absent:
        names = ", ".join(path.name for path in absent)
        raise ParityExportError(
            f"missing artifact(s): {names}. This script copies the recorded measurement rather than "
            f"re-running it, so it cannot proceed without them — re-record with `{REGENERATE}` "
            f"(from `backend/`), or restore the files if they were moved."
        )

    summary = json.loads((ARTIFACT_DIR / "libm-parity-summary.json").read_text(encoding="utf-8"))
    domain = json.loads((ARTIFACT_DIR / "libm-parity-domain.json").read_text(encoding="utf-8"))

    out.mkdir(parents=True, exist_ok=True)
    # Replace rather than merge: a stale artifact from an earlier measurement is a second opinion
    # about what glibc returned, and nothing downstream could tell which one it was reading.
    for stale in out.iterdir():
        if stale.is_file():
            stale.unlink()

    written: list[str] = []
    for source, name, _what in DELIVERED:
        shutil.copyfile(source, out / name)
        written.append(name)
    (out / "README.md").write_text(readme_text(summary, domain), encoding="utf-8")
    written.append("README.md")
    return sorted(written)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help=f"default {DEFAULT_OUT}")
    args = parser.parse_args(argv)

    out: Path = args.out
    written = deliver(out)

    summary = json.loads((out / "libm-parity-summary.json").read_text(encoding="utf-8"))
    print("=" * 78)
    print(f"LIBM PARITY   {out}")
    print("=" * 78)
    for name in written:
        print(f"  {name:<26} {(out / name).stat().st_size:>10,} bytes")
    print()
    print(
        f"sample rows        {summary['sample_rows']:,} of "
        f"{summary['total_distinct_inputs']:,} distinct inputs"
    )
    print(f"recorded against   {summary['environment']['libc']} · numpy {summary['environment']['numpy']}")
    print("These rows are INFORMATIONAL. The binding contract is generation-goldens/.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ParityExportError as error:
        print(f"\nLIBM PARITY EXPORT REFUSED\n{error}", file=sys.stderr)
        raise SystemExit(2) from None
