# SPDX-License-Identifier: AGPL-3.0-only
"""attempts and exam sessions

Revision ID: 1386dd39f51f
Revises: b618a9905ccb
Create Date: 2026-07-22 15:16:55.668552
"""
from __future__ import annotations

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '1386dd39f51f'
down_revision: str | None = 'b618a9905ccb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_exam_sessions_user_id_user'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_sessions'))
    )
    op.create_index(op.f('ix_exam_sessions_user_id'), 'exam_sessions', ['user_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('instance_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('given_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('state', sa.Enum('OPEN', 'ANSWERED', 'ABANDONED', name='attempt_state'), nullable=False),
    sa.Column('exam_session_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_session_id'], ['exam_sessions.id'], name=op.f('fk_attempts_exam_session_id_exam_sessions'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_attempts_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_attempts_user_id_user'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts'))
    )
    op.create_index(op.f('ix_attempts_exam_session_id'), 'attempts', ['exam_session_id'], unique=False)
    op.create_index(op.f('ix_attempts_exercise_id'), 'attempts', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_exercise_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_exam_session_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_exam_sessions_user_id'), table_name='exam_sessions')
    op.drop_table('exam_sessions')
    # ### end Alembic commands ###
    sa.Enum(name='attempt_state').drop(op.get_bind(), checkfirst=True)
