# SPDX-License-Identifier: AGPL-3.0-only
"""course skeleton and lesson completions

Revision ID: b618a9905ccb
Revises: e68898f4dcf0
Create Date: 2026-07-22 14:57:12.151589
"""
from __future__ import annotations

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b618a9905ccb'
down_revision: str | None = 'e68898f4dcf0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocks'))
    )
    op.create_table('modules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('block_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('assumes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], name=op.f('fk_modules_block_id_blocks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modules'))
    )
    op.create_index(op.f('ix_modules_block_id'), 'modules', ['block_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_lessons_module_id_modules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    op.create_index(op.f('ix_lessons_module_id'), 'lessons', ['module_id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('QUIZ', 'CALCULATION', 'SYNTHETIC_CHART', 'FIXTURE_CHART', name='exercise_type'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_exercises_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_exercises_module_id_modules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises'))
    )
    op.create_index(op.f('ix_exercises_lesson_id'), 'exercises', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_exercises_module_id'), 'exercises', ['module_id'], unique=False)
    op.create_table('lesson_completions',
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_completions_lesson_id_lessons'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_lesson_completions_user_id_user'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('user_id', 'lesson_id', name=op.f('pk_lesson_completions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_completions')
    op.drop_index(op.f('ix_exercises_module_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_lesson_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_lessons_module_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_modules_block_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_table('blocks')
    # ### end Alembic commands ###
    sa.Enum(name='exercise_type').drop(op.get_bind(), checkfirst=True)
